name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build site
        run: make build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "pear-dev"
          entrypoint: "./build/index.ts"
          root: "build"
