name: Pear.dev Pipeline
on: [push]

jobs:
  server-test:
    name: Server test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2

      - name: Use Deno Version 1.30.3
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.30.3

      - name: Lint Deno Module
        run: deno fmt --check

      - name: Test Deno Module
        run: deno test --allow-none

  deploy:
    name: Deploy
    needs: server-test
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build site
        run: make build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "pear-dev"
          entrypoint: "./index.ts"
          root: "build"
